### PR TITLE
⚠️ CONFLICT! Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request: CONFLICT #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/pe-reports.git pe-reports
    cd pe-reports
    git remote add skeleton https://github.com/cisagov/skeleton-python-library.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/CODEOWNERS 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may _append_ to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [x] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by schmelz21** [comment]
@mcdonnnj, @dav3r or @jsf9k  is this PR handled by your team or are we to take ownership of the tasks. Also if critical, should/could we expedite the merge of both this PR and https://github.com/cisagov/pe-reports/pull/6 at the same time. Thanks

**Comment by mcdonnnj** [comment]
> 
> 
> @mcdonnnj, @dav3r or @jsf9k is this PR handled by your team or are we to take ownership of the tasks. Also if critical, should/could we expedite the merge of both this PR and #6 at the same time. Thanks

@schmelz-ctr Your team should fix this PR for review following the directions in the description. Once that is done you should transition this from draft to ready for review. When creating a lineage PR [cisagov/action-lineage](https://github.com/cisagov/action-lineage) assigns to all CODEOWNERS. I have unassigned our dev team, but we will be asked for review once this PR is marked ready.

**Comment by jsf9k** [comment]
@schmelz-ctr - Note that one file was still conflicted when you asked for review.  I went ahead and fixed it in commit dbd6837, but this is something to watch for in the future with these lineage PRs.  In fact, if the title of the PR starts with "CONFLICT!" then you can be sure that there is a conflict lurking somewhere, and the main description of the PR explains how to correctly resolve the conflict so please read it carefully.  If you see a conflict that you don't know how to resolve, you can always ask one of us for help.  This was probably such a case, since we were removing a CISA dev who no longer works here.

Anyway, thanks for taking point on this one.

**Review by jsf9k — APPROVED** [review]

**Comment by schmelz21** [comment]
> @schmelz-ctr - Note that one file was still conflicted when you asked for review. I went ahead and fixed it in commit [dbd6837](https://github.com/cisagov/pe-reports/commit/dbd6837019c94c33f19effc8716892c4a9d68461), but this is something to watch for in the future with these lineage PRs. In fact, if the title of the PR starts with "CONFLICT!" then you can be sure that there is a conflict lurking somewhere, and the main description of the PR explains how to correctly resolve the conflict so please read it carefully. If you see a conflict that you don't know how to resolve, you can always ask one of us for help. This was probably such a case, since we were removing a CISA dev who no longer works here.
> 
> Anyway, thanks for taking point on this one.

@jsf9k , yes see the issue. I thought that was caught in the CODEOWNERS add command. Thanks for correcting and will look for something like that in any future conflicts.

**Review by mcdonnnj — APPROVED** [review]
LGTM ✔

**Comment by schmelz21** [comment]
> LGTM ✔

Ok, I will continue with the merge.

**Pull request merged**
