### PR TITLE
Add dark web schema to sql

### LINKED ISSUE #35: Dark Web Database Schema
# 💡 Summary #

Show database schema for domain masquerading data

## Motivation and context ##

To support database creation and use. For now, will be used solely for the rest of the team to referance.

## Implementation notes ##

- create at least one table that emulates how the data will be stored
- add to the data_schema.sql file located [here](https://github.com/cisagov/pe-reports/tree/develop/src/pe_reports/data)

## Acceptance criteria ##

- [ ] At least one table is created
- [ ] Each field needed for the report is included
- [ ] Table is commented out

### PR DESCRIPTION
**Pull request by schmelz21**
## 🗣 Description ##

To run dark web scans, tables addressing particular organizational assets and dark web output are required. At a minimum, tables for the organization includes; `alias`, `domains`, `ip_addresses`, `executives`. For the collection of output the following tables are required; `mentions`, `alerts`, `forums`, `threats`,` top_cves`. If a corresponding table already exist at merge, the preexisting table will be used. 

## 💭 Motivation and context ##
Adding the minimum required tables to` data/data_schema.sql `will support dark web scans. This effort also leads to the ability for multiple users to build out a database for P&E Reports 1.0.0.

Out of Scope but available tables include:
- organization: bins, cves, host_names, mac_addresses, network_names, products, third_parties
- output: dve

## 🧪 Testing ##

To test: data/data_schema.sql runs successfully and builds out schema. The environment is a local Postgres database. No other `pe-reports` code should be altered

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.

### CODE REVIEW

**Comment by schmelz21** [comment]
@stewartl97 , @cduhn17, @aloftus23 please see commit 42f58ab. I created the 2 tables `alias` for review. One following current sql and one incorporating Postgres SERIAL as primary key. Since we are pretty far as a Postgres solution, do we want to incorporate serial or stay as generic as possible?? I will build out the rest based on answers.

**Comment by aloftus23** [comment]
> @stewartl97 , @cduhn17, @aloftus23 please see commit [42f58ab](https://github.com/cisagov/pe-reports/commit/42f58ab81b422777ac30de625582c404f6f38e16). I created the 2 tables `alias` for review. One following current sql and one incorporating Postgres SERIAL as primary key. Since we are pretty far as a Postgres solution, do we want to incorporate serial or stay as generic as possible?? I will build out the rest based on answers.

I think we should use Serial whenever we don't care about the actual value of the primary key (just that it's unique). For instance, I think organization_id should not be Serial since there's only 24 and we can use the values when analyzing other tables. Does alias have any other use beyond being a unique identifier? **Edit: This is my take on it. Curious what @stewartl97  and @cduhn17 think.

**Comment by schmelz21** [comment]
> > @stewartl97 , @cduhn17, @aloftus23 please see commit [42f58ab](https://github.com/cisagov/pe-reports/commit/42f58ab81b422777ac30de625582c404f6f38e16). I created the 2 tables `alias` for review. One following current sql and one incorporating Postgres SERIAL as primary key. Since we are pretty far as a Postgres solution, do we want to incorporate serial or stay as generic as possible?? I will build out the rest based on answers.
> 
> I think we should use Serial whenever we don't care about the actual value of the primary key (just that it's unique). For instance, I think organization_id should not be Serial since there's only 24 and we can use the values when analyzing other tables. Does alias have any other use beyond being a unique identifier? **Edit: This is my take on it. Curious what @stewartl97 and @cduhn17 think.

So `alias` is used for dark web mentions.. which is a query of terms agains the source. `organization_id` being a One to Many.. 
i.e. 0001 ---> "Department of Homeland Security", "USDepartmentodHomelandSecurity", "DHS" and at the same time querying data from `domains` and `ip_addresses`.

**Comment by aloftus23** [comment]
> > > @stewartl97 , @cduhn17, @aloftus23 please see commit [42f58ab](https://github.com/cisagov/pe-reports/commit/42f58ab81b422777ac30de625582c404f6f38e16). I created the 2 tables `alias` for review. One following current sql and one incorporating Postgres SERIAL as primary key. Since we are pretty far as a Postgres solution, do we want to incorporate serial or stay as generic as possible?? I will build out the rest based on answers.
> > 
> > 
> > I think we should use Serial whenever we don't care about the actual value of the primary key (just that it's unique). For instance, I think organization_id should not be Serial since there's only 24 and we can use the values when analyzing other tables. Does alias have any other use beyond being a unique identifier? **Edit: This is my take on it. Curious what @stewartl97 and @cduhn17 think.
> 
> So `alias` is used for dark web mentions.. which is a query of terms agains the source. `organization_id` being a One to Many..
> i.e. 0001 ---> "Department of Homeland Security", "USDepartmentodHomelandSecurity", "DHS" and at the same time querying data from `domains` and `ip_addresses`.

Oh ok, then I think Serial is the "best practice" for this.

**Review by cduhn17 — APPROVED** [review]
The use of serial IMO is just a clean way to alias the the organization in a foreign key relation. In this instance its optional to use serial and doesn't add any real functional use. No further changes at this time.

**Comment by schmelz21** [comment]
@cduhn17 @DJensen94 @aloftus23 please review. I also added a pg mapping to PE Teams Folder:
**_Posture and Exposure/Temporary/Pull_Request_43_sql_layout_**. 

I held off in adding any reference tables, views or added data not used in round 1.0.0 mock-up to avoid any unforeseen issues. Let me know if I need to alter or expand on the structure.

**Review by jsf9k — APPROVED** [review]

**Review by DJensen94 — APPROVED** [review]

**Review by aloftus23 — APPROVED** [review]
Looks good!

**Pull request merged**
