### PR TITLE
Cd working v1.0

### PR DESCRIPTION
**Pull request by cduhn17**
# Solutions to Issues 21,23,24 #

## 🗣 Description ##

- Solve issue# [21](https://github.com/cisagov/pe-reports/issues/21)
- Solve issue# [23](https://github.com/cisagov/pe-reports/issues/23)
- Solve issue# [24](https://github.com/cisagov/pe-reports/issues/24)

## 💭 Motivation and context ##

- Issue [21](https://github.com/cisagov/pe-reports/issues/21) Initializes variable values, so the software will continue without errors if there are no values returned
- Issue [23](https://github.com/cisagov/pe-reports/issues/23) There are some related Bandit issues [PyCQA/Bandit#455](https://github.com/PyCQA/bandit/issues/455) and [PyCQA/bandit#333](https://github.com/PyCQA/bandit/issues/333#issuecomment-404103697) that justify module 'subprocess' usage.  This issue may be reinstated after further review.
- Issue [24](https://github.com/cisagov/pe-reports/issues/24) There is a security concern. The `eval()` has been replaced with `ast.literal_eval()`.

## ✅ Checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by schmelz21** [comment]
@cduhn17, can you take a look at these two items:
1. In loading in the new code and stepping through its clean-up, can we carry over the work in done in "develop" that includes the appropriete references of "TODOs" to Issues. For example - [this commit](https://github.com/cisagov/pe-reports/pull/6/commits/f3a1c85ce64c2b61e89e27e135f5e28b746cc2c0). Other than the issues addressed in this PR most will still be outstanding and can be addressed as we go.
2. Tests - we should adjust the following test to handle the new command-line arguments. This should allow us to pass all checks.
```
def test_log_levels(level):
    """Validate commandline log-level arguments."""
    with patch.object(
        sys,
        "argv",
        [
            "pe_reports",
            "2021-01-01",
            "input/",
            "output/",
            f"--log-level={level}",
        ],
    ):
```

**Comment by schmelz21** [comment]
@cduhn17, I referenced PR https://github.com/cisagov/pe-reports/pull/33, as a quick resolve to the tests issues presented in this PR.

**Comment by schmelz21** [comment]
@cduhn17 when you get a moment can you update the title/description with brief explanation to issues. Also looks like we can link Issue #23 with PR  https://github.com/cisagov/pe-reports/pull/33 and remove it from this PR.

**Comment by stewartl97** [comment]
As a note to all involved, the PRs #31 and #33 are extremely old and only valid for our LookingGlass data pulls for which the contract ends on 9/30 and they will be OBE.  Is there any possibility we can have them completed before I have to redirect the team to continue other work?

**Comment by schmelz21** [comment]
Closing pull-request as efforts to update the `main `branch have been canceled. Routines used in version 0.1.1 have been sunsetted with no future plans to update.

**Pull request closed without merging**
