### PR TITLE
Update fixes for command injections at bulletin_generator

### PR DESCRIPTION
**Pull request by cduhn17**
#  #

## 🗣 Description ##

Sanitize input from `input` variables. 
Revove the following code associated with htmx.js:

- The method o embeds untrusted data in generated output with body, at line 148 of src/pe_reports/static/js/htmx.js. This
   untrusted data is embedded into the output without proper sanitization or encoding, enabling an attacker to inject
   malicious code into the generated web-page src/pe_reports/js/htmx.js line 1224,151, 1321, 722. Also removed associated 
   code in *.css as the styles are no longer need once htmx.js is removed (see https://github.com/cisagov/pe-reports/pull/596).

## 💭 Motivation and context ##

Based on the input that is possible it is a best practice to remove the chance of command execution.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Revert dependencies to default branches.
- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Review by aloftus23 — APPROVED** [review]
Looks good.

**Review by dav3r — COMMENTED** [review]
This looks fine to me, but I am unclear on how the changes in the files other than `src/pe_reports/helpers/bulletin/bulletin_generator.py` help prevent command injection.  Can someone please explain that?

**Comment by cduhn17** [comment]
@dav3r , 

The other changes are third part libs, so we just removed them to pass the checks. Its not our evaluation, that is all of the information that I have at this point.

**Comment by dav3r** [comment]
> @dav3r ,
> 
> The other changes are third part libs, so we just removed them to pass the checks. Its not our evaluation, that is all of the information that I have at this point.

Which third party libraries are you removing?  I was referring to the HTML changes [here](https://github.com/cisagov/pe-reports/pull/599/files#diff-f6effbb8b15e2da0ca7d1e2ec07fa6c8ad5cfb9690ad204a0b366de755021b0aL123), [here](https://github.com/cisagov/pe-reports/pull/599/files#diff-2ca10c2fa0380311e4e1df7d1e5ea40c6122bfc5758e9f35628585bfe81271f4L5-L7), and [here](https://github.com/cisagov/pe-reports/pull/599/files#diff-15ff57cf81c6902607b960ac47433ef44dcd6a46d8f19ae88b19746a6439293bL27).  Regardless, you should update the content in the PR's description to document why these changes are included.

**Comment by cduhn17** [comment]
@dav3r , 

I have updated the PR description. The third-party js lib is HTMX js.

**Comment by dav3r** [comment]
> I have updated the PR description. The third-party js lib is HTMX js.

@cduhn17 I don't see any updates to this PR's description - it looks like there haven't been any edits in 2 days.

**Comment by cduhn17** [comment]
@dav3r , 
Should be updated now.

**Review by dav3r — APPROVED** [review]
Looks good to me now, thanks!

BTW, I edited the PR description to include a reference to https://github.com/cisagov/pe-reports/pull/596 for some context.

**Pull request merged**
