### PR TITLE
Update SQL schema

### PR DESCRIPTION
**Pull request by DJensen94**
Add additional tables to ensure we can track all assets associated to each organization

#  #

## 🗣 Description ##
We currently don't have tables to track our asset tracking process, this PR is to add new tables that will hold domain and IP data for each organization

## 🧪 Testing ##

Same testing as past SQL creation statement updates

## ✅ Checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by schmelz21** [comment]
@DJensen94 and @cduhn17 might be worth getting this up to date and pushed as we head toward implying metrics and charts. Ideally, to run tests locally on a set of 'dummy' data. 
What do you think...?

**Comment by cduhn17** [comment]
@DJensen94 @schmelz21 
I think that is a great idea getting this PR merged.

**Review by aloftus23 — APPROVED** [review]
Look good

**Review by cduhn17 — APPROVED** [review]
Look good.

**Pull request merged**
